---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build-with-mono
  image: mono
  commands:
  - nuget restore HomeGenie_Linux/HomeGenie_Linux.sln
  - msbuild -p:Configuration=Debug -v:normal HomeGenie_Linux/HomeGenie_Linux.sln

- name: test
  image: mono
  commands:
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe HomeGenie.UnitTests/bin/Debug/HomeGenie.UnitTests.dll

- name: copy artifacts
  image: alpine
  commands:
  - cp -R HomeGenie/bin/Debug/. Utils/docker/hg_compiled/
  when:
    ref:
    - refs/tags/V*

- name: build images
  image: docker:19.03.5-dind
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - cd Utils/docker
  - docker build -f hgbe.dockerfile --build-arg arch=amd64 -t bounz/hgbe:${DRONE_TAG}-amd64 -t bounz/hgbe:latest-amd64 .
  - docker build -f hgbe.dockerfile --build-arg arch=arm32v7 -t bounz/hgbe:${DRONE_TAG}-arm32v7 -t bounz/hgbe:latest-arm32v7 .
  - docker push bounz/hgbe:${DRONE_TAG}-amd64
  - docker push bounz/hgbe:latest-amd64
  - docker push bounz/hgbe:${DRONE_TAG}-arm32v7
  - docker push bounz/hgbe:latest-arm32v7
  environment:
    PASSWORD:
      from_secret: docker_password
    USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  when:
    ref:
    - refs/tags/V*

- name: create manifest
  image: docker:19.03.5-dind
  commands:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker login -u $USERNAME -p $PASSWORD
  - "docker manifest create bounz/hgbe:${DRONE_TAG} bounz/hgbe:${DRONE_TAG}-amd64 bounz/hgbe:${DRONE_TAG}-arm32v7"
  - "docker manifest push bounz/hgbe:${DRONE_TAG}"
  - docker manifest create bounz/hgbe:latest bounz/hgbe:latest-amd64 bounz/hgbe:latest-arm32v7
  - docker manifest push bounz/hgbe:latest
  environment:
    PASSWORD:
      from_secret: docker_password
    USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  when:
    ref:
    - refs/tags/V*

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: build-base-image

platform:
  os: linux
  arch: amd64

steps:
- name: build base image amd64
  image: docker:19.03.5-dind
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - cd Utils/docker
  - "docker build -f hgbe.base.x86.dockerfile --build-arg arch=amd64 -t bounz/hgbe.base:${DRONE_TAG:11}-amd64 -t bounz/hgbe.base:latest-amd64 ."
  - "docker push bounz/hgbe.base:${DRONE_TAG:11}-amd64"
  - docker push bounz/hgbe.base:latest-amd64
  environment:
    PASSWORD:
      from_secret: docker_password
    USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: build base image arm32v7
  image: docker:19.03.5-dind
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - cd Utils/docker
  - "docker build -f hgbe.base.dockerfile --build-arg arch=arm32v7 --build-arg qemu=arm -t bounz/hgbe.base:${DRONE_TAG:11}-arm32v7 -t bounz/hgbe.base:latest-arm32v7 ."
  - "docker push bounz/hgbe.base:${DRONE_TAG:11}-arm32v7"
  - docker push bounz/hgbe.base:latest-arm32v7
  environment:
    PASSWORD:
      from_secret: docker_password
    USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: create manifest
  image: docker:19.03.5-dind
  commands:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker login -u $USERNAME -p $PASSWORD
  - "docker manifest create bounz/hgbe.base:${DRONE_TAG:11} bounz/hgbe.base:${DRONE_TAG:11}-amd64 bounz/hgbe.base:${DRONE_TAG:11}-arm32v7"
  - "docker manifest push bounz/hgbe.base:${DRONE_TAG:11}"
  - docker manifest create bounz/hgbe.base:latest bounz/hgbe.base:latest-amd64 bounz/hgbe.base:latest-arm32v7
  - docker manifest push bounz/hgbe.base:latest
  environment:
    PASSWORD:
      from_secret: docker_password
    USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock

trigger:
  ref:
  - refs/tags/base-image-v*
