kind: pipeline
type: docker
name: build

steps:
  - name: build-with-mono
    image: mono
    commands:
      - nuget restore HomeGenie_Linux/HomeGenie_Linux.sln
      - xbuild /p:Configuration=Debug HomeGenie_Linux/HomeGenie_Linux.sln

  - name: test
    image: mono
    commands:
      - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
      - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe HomeGenie.UnitTests/bin/Debug/HomeGenie.UnitTests.dll

---
kind: pipeline
type: docker
name: buildx

steps:
  - name: build-on-amd64
    image: docker:19.03.5-dind
    environment:
      DOCKER_DRIVER: overlay2
      USERNAME:
       from_secret: docker_username
      PASSWORD:
       from_secret: docker_password
    volumes:
    - name: docker.sock
      path: /var/run/docker.sock
    - name: imagecache
      path: /var/lib/docker
    commands:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker login -u $USERNAME -p $PASSWORD
    - mkdir -p ~/.docker/cli-plugins
    - wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker buildx create --use
    - cd Utils/docker
    - docker buildx build --platform linux/amd64,linux/arm/v7 -f hgbe.dockerfile -t bounz/hgbetest --push .
  
volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock

- name: imagecache
  host:
    path: /var/lib/docker

---
kind: pipeline
type: docker
name: baseimage

steps:
  - name: build-on-amd64
    image: docker:19.03.5-dind
    environment:
      DOCKER_DRIVER: overlay2
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    volumes:
    - name: docker.sock
      path: /var/run/docker.sock
    - name: imagecache
      path: /var/lib/docker
    commands:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker login -u $USERNAME -p $PASSWORD
    - mkdir -p ~/.docker/cli-plugins
    - wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker buildx create --use
    - cd Utils/docker
    - docker buildx build --platform linux/amd64,linux/arm/v7 -f hgbe.base.dockerfile -t bounz/hgbe.base --push .

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock

- name: imagecache
  host:
    path: /var/lib/docker

---
kind: pipeline
type: docker
name: armv7

steps:
  - name: build-on-amd64
    image: docker:19.03.5-dind
    environment:
      DOCKER_DRIVER: overlay2
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    volumes:
    - name: docker.sock
      path: /var/run/docker.sock
    commands:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker login -u $USERNAME -p $PASSWORD
    - docker run --rm --privileged multiarch/qemu-user-static --reset
    - cd Utils/docker
    - ls -la /usr/bin
    - ls -la
    - docker build -f hgbe_arm32.dockerfile -t bounz/hgbe.arm32:t2 .
    - docker push bounz/hgbe.arm32:t2

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
