#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.

version: 1.1.{build}
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
branches:
  only:
  - master
  - /V.*/
clone_folder: c:\projects\homegenie

#---------------------------------#
#     install configuration       #
#---------------------------------#

install:
  # - git clone https://github.com/genielabs/mig-service-dotnet.git
  
  # Install innosetup
  - choco install -y curl innosetup

  # Install doxy
  #- choco install doxygen.portable

  # Download wpkg and install
  - appveyor downloadfile https://downloads.sourceforge.net/project/unigw/wpkg/1.0.0/wpkg-1.0.0-amd64.exe
  - wpkg-1.0.0-amd64.exe /S
  
  # Install 7zipcommandline
  - nuget install 7ZipCLI -ExcludeVersion # http://help.appveyor.com/discussions/suggestions/702-pre-install-7zipcommandline
  - set PATH=%appveyor_build_folder%\packages\7ZipCLI\tools;"C:\Program Files (x86)\Inno Setup 5";%PATH%

#---------------------------------#
#      build configuration        #
#---------------------------------#

#build:
#  project: c:\projects\homegenie\HomeGenie_Windows\HomeGenie_VS10.sln
#  verbosity: minimal

build_script:
- cmd: >-
    msbuild c:\projects\homegenie\BaseFiles\Windows\Windows.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild c:\projects\homegenie\HomeGenie_Windows\HomeGenie_VS10.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#---------------------------------#
#       Post build steps          #
#---------------------------------#

# Generate documentation
#- cd C:\projects\homegenie\Doxy
#- doxygen.exe "C:\projects\homegenie\Doxy\Doxyfile"
#- cd C:\projects\homegenie

#---------------------------------#
#  pre deployment configuration   #
#---------------------------------#

before_deploy:
  - ps: . "$($env:APPVEYOR_BUILD_FOLDER)\HomeGenie_Linux\Packager\builddeb.ps1"

  # Call wpkg to create .deb package
  - C:\WPKG\bin\wpkg.exe --build c:\projects\homegenie\release --output-dir c:\projects\homegenie\release --verbose

#---------------------------------#
#         create TGZ file         #
#---------------------------------#

  - 7za a -ttar "c:\projects\homegenie\release\homegenie_%APPVEYOR_BUILD_VERSION%_all.tgz" "C:\projects\homegenie\HomeGenie\bin\%CONFIGURATION%\*""

#---------------------------------#
# create windows setup (exe) file #
#---------------------------------#

  - iscc c:\projects\HomeGenie\HomeGenie_Windows\Packager\setup.iss /Oc:\projects\homegenie\release /Fhomegenie_%APPVEYOR_BUILD_VERSION%_all

#---------------------------------#
#         Push Artifacts          #
#---------------------------------#

  - appveyor PushArtifact "release\homegenie_%APPVEYOR_BUILD_VERSION%_all.deb"
  - appveyor PushArtifact "release\homegenie_%APPVEYOR_BUILD_VERSION%_all.tgz"
  - appveyor PushArtifact "release\homegenie_%APPVEYOR_BUILD_VERSION%_all.exe"

#---------------------------------#
#           Do Release            #
#---------------------------------#

deploy:
  release: V$(appveyor_build_version)
  description: 'Homegenie (Bounz Edition) version $(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: MkEJm5U8V0NeUQ7cz7EcojV4XT1YUSo3gEFWrKDuoHQXx1+eTGe8l1ePdSnUivm2
  # artifact: release\**\*.deb 
  draft: false
  prerelease: true
  on:
    branch: master                  # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only
